/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.DAO.cursosDAO;
import Model.DAO.disciplinasDAO;
import javax.swing.table.DefaultTableModel;
import Model.DAO.alunosDAO;
import Model.DAO.professoresDAO;

/**
 *
 * @author William
 */
public class mostrar extends javax.swing.JFrame {

    alunosDAO aDAO = new alunosDAO();
    disciplinasDAO dDAO = new disciplinasDAO();
    cursosDAO cDAO = new cursosDAO();
    professoresDAO pDAO = new professoresDAO();
    /**
     * Creates new form Alunos
     */
    public mostrar() {
        initComponents();
    }
    
    void setTitulos (String t,String[] columns) {
        setTitle(t);
        mostrarTable.setModel(new javax.swing.table.DefaultTableModel(new Object [][] {}, columns));
    }  
    
    public void readAlunosTable (){
        String[] columns = {"Matricula","Nome","Data nasc","Curso"};
        setTitulos("Alunos",columns);
        DefaultTableModel modelo = (DefaultTableModel) mostrarTable.getModel();
        modelo.setNumRows(0);
        aDAO.read().forEach((a) -> {
            modelo.addRow(new Object[]{
                a.getMatricula(),
                a.getNomeAluno(),
                a.getDataNascAluno(),                
                a.getNomeCurso()
            });
        });
    }
    
    public void readDisciplinasTable (){
        String[] columns = {"Código","Nome Disc."};        
        setTitulos("Disciplinas",columns);
        DefaultTableModel modelo = (DefaultTableModel) mostrarTable.getModel();
        modelo.setNumRows(0);
        dDAO.read().forEach((d) -> {
            modelo.addRow(new Object[]{
                d.getCodDisc(),
                d.getNomeDisc()
            });
        });
    }    

    public void readCursosTable (){
        String[] columns = {"Código","Nome curso"};            
        setTitulos("Cursos",columns);
        DefaultTableModel modelo = (DefaultTableModel) mostrarTable.getModel();
        modelo.setNumRows(0);
        cDAO.read().forEach((c) -> {
            modelo.addRow(new Object[]{
                c.getCodCurso(),
                c.getNomeCurso()
            });
        });
    }   
    
    public void readProfessoresTable (){
        String[] columns = {"Profº Id","Nome profº","Graduação"};           
        setTitulos("Professores",columns);
        DefaultTableModel modelo = (DefaultTableModel) mostrarTable.getModel();
        modelo.setNumRows(0);
        pDAO.read().forEach((c) -> {
            modelo.addRow(new Object[]{
                c.getIdentProf(),
                c.getNomeProf(),
                c.getEspecProf()
            });
        });
    }      
    
    public void readCursosDisciplinasTable (){
        String[] columns = {"Nome Curso","Nome Disc."};        
        setTitulos("Cursos/Disciplinas",columns);
        DefaultTableModel modelo = (DefaultTableModel) mostrarTable.getModel();
        modelo.setNumRows(0);
        dDAO.readCurso().forEach((c) -> {
            modelo.addRow(new Object[]{
                c.getNomeCurso(),
                c.getNomeDisc()
            });
        });
    }  
    
    public void readProfessoresDisciplinasTable (){
        String[] columns = {"Professor","Nome Disc."};        
        setTitulos("Professores/Disciplinas",columns);
        DefaultTableModel modelo = (DefaultTableModel) mostrarTable.getModel();
        modelo.setNumRows(0);
        pDAO.readDisciplinas().forEach((c) -> {
            modelo.addRow(new Object[]{
                c.getNomeProf(),
                c.getNomeDisc()
            });
        });
    }      

    public void readCursosProfessoresTable (){
        String[] columns = {"Curso","Professor"};        
        setTitulos("Cursos/Professores",columns);
        DefaultTableModel modelo = (DefaultTableModel) mostrarTable.getModel();
        modelo.setNumRows(0);
        pDAO.readCursos().forEach((c) -> {
            modelo.addRow(new Object[]{
                c.getNomeCurso(),
                c.getNomeProf()
            });
        });
    }         
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        mostrarTable = new javax.swing.JTable();

        mostrarTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Matricula", "Nome"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(mostrarTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable mostrarTable;
    // End of variables declaration//GEN-END:variables
}
